# Generated by Django 5.1.5 on 2025-02-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutclass',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9),
        ),
        migrations.AlterField(
            model_name='workoutclass',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='workoutclass',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
