# Generated by Django 5.1.6 on 2025-03-07 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutclass',
            name='end_time',
        ),
    ]
